# Generated by Django 4.1.1 on 2022-09-10 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_rename_panelfortasks_panel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='panel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='notes.panel'),
            preserve_default=False,
        ),
    ]
